"""Generate a benchmark-quality scorecard across several public HF jailbreak
datasets, using the foundry's own audit + (corpus-only) staleness scoring.

Run:  python scripts/hf_scorecard.py  [--limit 300] [--output reports/samples/hf_scorecard.md]

No API key needed — this is pure corpus analysis. Network is used to pull the
datasets. Prompts are never written out; only aggregate counts.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from redteam.corpora._filters import filter_cases
from redteam.corpora.huggingface import load_hf_dataset
from redteam.corpora.quality import audit_corpus
from redteam.staleness import score_staleness

# (dataset id, prompt column, HF config or None, pinned commit SHA). All public
# + non-gated. Pinned so re-running reproduces the committed scorecard numbers.
DATASETS: list[tuple[str, str, str | None, str]] = [
    (
        "rubend18/ChatGPT-Jailbreak-Prompts",
        "Prompt",
        None,
        "b93e4982f8f8ad2d82c6d35e3c00d161844ad70a",
    ),
    (
        "jackhhao/jailbreak-classification",
        "prompt",
        None,
        "2f2ceeb39658696fd3f462403562b6eea5306287",
    ),
    (
        "TrustAIRLab/in-the-wild-jailbreak-prompts",
        "prompt",
        "jailbreak_2023_12_25",
        "a10aab8eff1c73165a442d4464dce192bd28b9c5",
    ),
    ("deadbits/vigil-jailbreak-ada-002", "text", None, "9e42942ca146a8ac7fd746f6e6e1439a4ac6e2e5"),
]


def _component(report_components: list, name: str) -> float | None:
    for c in report_components:
        if c.name == name:
            return c.score
    return None


def _top_family(coverage: dict[str, int]) -> str:
    hits = {k: v for k, v in coverage.items() if v > 0}
    if not hits:
        return "none detected"
    fam, n = max(hits.items(), key=lambda kv: kv[1])
    return f"{fam} ({n})"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=300)
    ap.add_argument("--output", type=Path, default=Path("reports/samples/hf_scorecard.md"))
    args = ap.parse_args()

    rows: list[str] = []
    for name, col, cfg, rev in DATASETS:
        try:
            raw = load_hf_dataset(
                name, prompt_column=col, config=cfg, revision=rev, limit=args.limit
            )
        except Exception as exc:
            rows.append(f"| `{name}` | load failed: {str(exc)[:60]} | | | | | | |")
            continue
        kept, excluded = filter_cases(raw)
        if not kept:
            rows.append(f"| `{name}` | {len(raw)} | {len(excluded)} | all excluded | | | | |")
            continue
        rep = audit_corpus(kept)
        stale = score_staleness(kept)
        obsolete = _component(stale.components, "obsolete_pattern")
        langs = "+".join(sorted(rep.language_coverage)) or "-"
        score = f"{stale.staleness_score:.2f}" if stale.staleness_score is not None else "-"
        obs = f"{obsolete:.2f}" if obsolete is not None else "-"
        rows.append(
            f"| `{name}` | {rep.n_cases} | {len(excluded)} | "
            f"{rep.duplicate_rate:.1%} | {rep.n_near_duplicate_pairs} | "
            f"{langs} | {_top_family(rep.attack_family_coverage)} | {obs} | {score} |"
        )

    out = [
        "# Benchmark-quality scorecard — public jailbreak datasets",
        "",
        "Generated by `scripts/hf_scorecard.py` using this repo's `corpora audit-hf`",
        f"+ corpus-only `staleness` scoring (first {args.limit} rows per dataset,",
        "post-safety-filter). Corpus-only staleness uses the obsolete-meme and",
        "duplication signals only (no model runs), so it is a **low-confidence**,",
        "corpus-side proxy — a high value flags a dataset for a closer look.",
        "",
        "> Datasets are **pinned** to specific commits (see `scripts/hf_scorecard.py`),",
        "> so re-running reproduces these numbers. Aggregate counts only; no prompts.",
        "",
        "| dataset | kept | excluded | exact-dup | near-dup pairs | languages | top attack family | obsolete-meme | staleness (corpus) |",
        "| --- | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: |",
        *rows,
        "",
        "Columns: **kept/excluded** = rows surviving / dropped by the safety filter;",
        "**exact-dup** = share of duplicate cases; **near-dup pairs** = token-Jaccard",
        "≥ 0.85; **obsolete-meme** = fraction leaning on dated jailbreak memes",
        "(DAN/AIM/…); **staleness (corpus)** = weighted obsolete + duplication proxy.",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
