"""The published source distribution may contain only files git tracks.

An sdist is built from the *directory*, not from the git index. Hatchling applies
`.gitignore` files it finds inside the project and has no knowledge of a
contributor's global gitignore (`core.excludesFile`), so anything hidden there is
absent from `git status`, absent from any diff a reviewer reads, absent from CI —
and packaged. PyPI uploads cannot be unpublished.

Before the allowlist in `pyproject.toml`, this project's sdist already contained
two files git does not track: `data/.gitkeep` and `results/.gitkeep`, both
covered by the repository's own `/data/` and `/results/` rules. Hatchling honoured
a `!` re-inclusion that git does not, which is the whole point — the backend's
file selection was not the repository's. Nothing escaped, because both files are
empty. The next such file would not have to be.

Three properties are pinned, in ascending order of strength:

1. The selection stays an allowlist. Deleting it restores the old behaviour,
   which is the regression that arms the defect.
2. No allowlist entry names a directory that is local-only for anyone.
3. **Every member of the built sdist is git-tracked.** This is the check that
   stops the class rather than the instances: every local-only file is untracked
   by construction, so none can reach the artifact without this going red — and
   it needs no list of what local tooling happens to be called.

Property 3 builds the sdist itself. A check that reads a build output it did not
produce is measuring a leftover, and there is a stale `dist/` in this working
tree to prove the point.
"""

from __future__ import annotations

import contextlib
import subprocess
import tarfile
import tomllib
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Directory names that are local-only for at least one contributor, whatever a
# future edit to the allowlist thinks.
LOCAL_ONLY_MARKERS = (
    ".claude",
    ".agents",
    ".codex",
    "graphify-out",
    ".venv",
    "dist",
    "build",
    "logs",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "htmlcov",
)

# Generated by the build backend, so tracked-ness does not apply.
GENERATED_MEMBERS = frozenset({"PKG-INFO"})

# Credential shapes, checked against the artifact regardless of tracked-ness.
# `.env` is matched as an exact filename: `.env.example` is a deliberate 725-byte
# template, tracked in git and correct to publish.
SECRET_FILENAMES = frozenset(
    {".env", ".netrc", "credentials.json", "service-account.json", "gcp-key.json", "id_rsa"}
)
SECRET_SUFFIXES = (".pem", ".key", ".pfx", ".p12", ".keystore", ".jks", ".ppk")


def _sdist_include() -> list[str]:
    """The declared allowlist, or an empty list if the section was deleted.

    Deleting the section is the regression, so it must reach an assertion with a
    readable message rather than a KeyError. The cost is that every test looping
    over this list would then pass vacuously, which is the failure mode this
    repository catalogues — so each of those asserts the list is non-empty first.
    """
    config = tomllib.loads((PROJECT_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    sdist = (
        config.get("tool", {}).get("hatch", {}).get("build", {}).get("targets", {}).get("sdist", {})
    )
    include = sdist.get("include", [])
    assert isinstance(include, list)
    return [str(entry) for entry in include]


def _tracked_paths() -> set[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


@pytest.fixture(scope="module")
def sdist_members(tmp_path_factory: pytest.TempPathFactory) -> frozenset[str]:
    """Build the sdist and return its member paths, project prefix stripped.

    Built in process from the project root into a temporary directory: never
    from `dist/`, which holds whatever a previous build left behind.
    """
    from hatchling.build import build_sdist

    out = tmp_path_factory.mktemp("sdist")
    with contextlib.chdir(PROJECT_ROOT):
        name = build_sdist(str(out))

    with tarfile.open(out / name) as archive:
        names = archive.getnames()

    # Every member is prefixed with `<name>-<version>/`.
    return frozenset(n.split("/", 1)[1] for n in names if "/" in n)


def test_sdist_selection_is_an_allowlist() -> None:
    assert _sdist_include(), (
        "The sdist include allowlist is empty. Without it hatchling packages the whole "
        "working tree minus the repository .gitignore, which is an exclude list that "
        "fails open: the next local cache directory is published without a warning."
    )


def test_allowlist_names_no_local_only_directory() -> None:
    include = _sdist_include()
    assert include, "nothing to check — see test_sdist_selection_is_an_allowlist"
    for entry in include:
        parts = entry.strip("/").split("/")
        for marker in LOCAL_ONLY_MARKERS:
            assert marker not in parts, (
                f"sdist allowlist entry {entry!r} names {marker!r}, which is local-only "
                "for at least one contributor and must not be published."
            )


def test_every_allowlist_entry_matches_a_tracked_file() -> None:
    """A stale entry is as much a defect as a dangerous one — it hides drift."""
    include = _sdist_include()
    assert include, "nothing to check — see test_sdist_selection_is_an_allowlist"
    tracked = _tracked_paths()
    for entry in include:
        rel = entry.strip("/")
        matched = rel in tracked or any(path.startswith(f"{rel}/") for path in tracked)
        assert matched, (
            f"sdist allowlist entry {entry!r} matches no git-tracked file. Either it is "
            "stale, or it names something untracked — which must never be packaged."
        )


def test_built_sdist_contains_only_tracked_files(sdist_members: frozenset[str]) -> None:
    """The check that stops the class.

    Named directories are not the danger; unnamed ones are. Anything local-only
    is untracked by construction, so this fires without knowing its name.
    """
    strays = sorted(sdist_members - _tracked_paths() - GENERATED_MEMBERS)
    assert strays == [], (
        f"the built sdist contains {len(strays)} file(s) git does not track: {strays}. "
        "Untracked files are exactly what a global gitignore hides, and publication "
        "is permanent."
    )


def test_built_sdist_carries_no_credential_shaped_file(sdist_members: frozenset[str]) -> None:
    """Checked against the artifact, independently of what git thinks.

    A secret that was committed by mistake is tracked, so the test above would
    pass it. This one does not care how it got there.
    """
    offenders = sorted(
        member
        for member in sdist_members
        if Path(member).name in SECRET_FILENAMES or member.endswith(SECRET_SUFFIXES)
    )
    assert offenders == [], f"credential-shaped files in the sdist: {offenders}"


def test_built_sdist_carries_what_the_package_needs(sdist_members: frozenset[str]) -> None:
    """An allowlist fails closed, so it can also fail closed on something needed."""
    for required in (
        "pyproject.toml",
        "README.md",
        "LICENSE",
        "src/redteam/__init__.py",
        "tests/unit/test_sdist_contents.py",
    ):
        assert required in sdist_members, f"{required!r} missing from the sdist"
